const REGISTER = 'REGISTER';
const REGISTERSUCCESS = 'REGISTERSUCCESS';
const REGISTERFAILED = 'REGISTERFAILED';
const SIGNIN = 'SIGNIN';
const SIGNINSUCCESS = 'SIGNINSUCCESS';
const SIGNINFAILED = 'SIGNINFAILED';
const SIGNUP = 'SIGNUP';

export default {
  REGISTER,
  REGISTERFAILED,
  REGISTERSUCCESS,
  SIGNUP,
  SIGNINFAILED,
  SIGNINSUCCESS,
  SIGNIN,
};
